### ISSUE TITLE
Missing @:tool

### ISSUE THREAD

**Issue by dazKind** [HaxeGodot/extern-generator#1]
When writing scripts for in-editor use it would help to have the ability to use [godot's `tool` mechanism](https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html) via Haxe's class metadata

**Comment by dazKind** [comment]
On Discord klabz pointed me towards the internal [`@:meta(..)`](https://github.com/HaxeFoundation/haxe/blob/development/src/generators/gencs.ml#L1954) and [`@:cs.using(..)`](https://github.com/HaxeFoundation/haxe/blob/development/src/generators/gencs.ml#L2885) compiler metadata.

This way it can be made to work.

```haxe
@:cs.using("Godot")
@:meta("Tool")
class LSystem extends Spatial {...
```

**Comment by ibilon** [comment]
I'll add a `@:tool` metadata, it'll be easier.

**Comment by ibilon** [comment]
Added something in https://github.com/HaxeGodot/extern-generator/commit/a7eea7c92e2bd7fc7d500b5e00662ada4b331d24, it adds the `[Godot.Tool]` as expected. But didn't know how to check, does it work?

**Comment by dazKind** [comment]
It works!

One question though. Right now we need a script to be included in some tscn in the project for the [Type to be registered for compilation](https://github.com/HaxeGodot/godot/blob/main/godot/Godot.hx#L118) to pick it up. That works great for all scripts that are gameplay related and inherit from one of the Node classes. But for editorscripts it's something we dont have/want. So the only way to compile such a script atm is to add it to a random node(Godot will complain about the wrong baseclass), open it in the editor's script editor and then run it like intended. But now, as long as this script hangs in the scene, you cant run your game anymore. 

This might actually be not a big deal, since it kinda makes sure you dont include editorscripts in a gamebuild but I'm not 100% sure if this should have a better approach. Any ideas?

**Comment by dazKind** [comment]
Even worse, I'm constantly running into errors with the script

![image](https://user-images.githubusercontent.com/5015415/117515958-05ac4d80-af98-11eb-8a97-a9d0a1e72acf.png)

**Comment by ibilon** [comment]
I guess every script in the script folders should be added to the compilation, regardless if they are attached to a node or not.
That's probably going to fail if you have a file `T.hx` without its main type `T`, but that's probably a fair limitation. And that'd be more userfriendly than forcing the scene to be saved.

**Comment by ibilon** [comment]
In https://github.com/HaxeGodot/extern-generator/commit/8abeda8911151e1865cec4bcff8aaac468a8fe37 I changed the script listing to be all files in the scripts folder. You don't need to attach your tool script to a node now.
